apiVersion: apps/v1
kind: Deployment
metadata:
    name: data-routing-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: data-routing-app 
    minReadySeconds: 10
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    template:
        metadata:
            labels:
                app: data-routing-app
        spec:
            containers:
                - name: data-routing-app 
                  image: graham/data_routing:1.0 

