apiVersion: v1
kind: Service
metadata:
    name: mongo-db 
    labels:
        app: mongodb 
spec:
    type: NodePort
    ports:
        - port: 27017
          nodePort: 30011
          protocol: TCP
    selector:
        app: mongodb

