apiVersion: v1
kind: Service
metadata:
    name: postgres-db 
    labels:
        app: postgres 
spec:
    type: NodePort
    ports:
        - port: 5432
          nodePort: 30031
          protocol: TCP
    selector:
        app: postgres

