apiVersion: apps/v1
kind: Deployment
metadata:
    name: sensor-app-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: sensor-app 
    minReadySeconds: 10
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    template:
        metadata:
            labels:
                app: sensor-app 
        spec:
            containers:
                - name: sensor-app 
                  image: graham/sensor-app:1.0 

