version: '3'
services:
  jupyter-notebook:
    build: ./jupyter_notebook
    image: "graham/jupyter_notebook:1.0"
    ports:
      - "8888:8888"
  data_routing:
    build: ./data_routing/
    image: "graham/data_routing:1.0"
    depends_on:
        - "mosquitto"
        - "mongo_db"
  mongo_db:
    image: "mongo"
    ports:
        - "27017:27017"
  postgres_db:
    environment: 
      - POSTGRES_PASSWORD=postgres
    image: "postgres"
  mosquitto:
    image: "eclipse-mosquitto"
    ports:
        - "1883:1883"

