version: '3'
services:
  datalab-notebook:
    build: ./jupyter_notebook
    image: "graham/jupyter_notebook:1.0"
    user: root
    ports:
      - "8000:8000"
  data-routing:
    build: ./data_routing/
    image: "graham/data_routing:1.0"
    depends_on:
        - "mosquitto"
        - "mongo-db"
  mongo-db:
    image: "mongo"
    ports:
        - "27017:27017"
  postgres-db:
    environment: 
      - POSTGRES_PASSWORD=postgres
    image: "postgres"
  mosquitto:
    image: "eclipse-mosquitto"
    ports:
        - "1883:1883"

