apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: jupyter-notebook
  name: jupyter-notebook
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jupyter-notebook
    spec:
      containers:
      - image: jupyter_notebook
        name: jupyter-notebook
        ports:
        - containerPort: 8888
        resources: {}
      restartPolicy: Always
status: {}
