apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: sensor-app
  name: sensor-app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sensor-app
    spec:
      containers:
      - image: sensor_app
        name: sensor-app
        resources: {}
      restartPolicy: Always
status: {}
